import type { Metadata } from "next";

import Layout from "@/components/Layout";

import MainProvider from "@/providers/MainProvider";

export const metadata: Metadata = {
	title: "Gamenote | Store",
	description: "Generated by Abdullz team",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body style={{ margin: 0, padding: 0 }}>
				<MainProvider>
					<Layout>{children}</Layout>
				</MainProvider>
			</body>
		</html>
	);
}
